const CLUBES = [
  {
    id: "flamengo",
    nome: "Flamengo",
    sigla: "FLA",
    cor: "#E8000D",
    jogadores: [
      { id: "p01", nome: "Rossi",        posicao: "GOL", overall: 82 },
      { id: "p02", nome: "Varela",        posicao: "DEF", overall: 75 },
      { id: "p03", nome: "Léo Pereira",   posicao: "DEF", overall: 78 },
      { id: "p04", nome: "Ayrton Lucas",  posicao: "DEF", overall: 74 },
      { id: "p05", nome: "Fabrício Bruno",posicao: "DEF", overall: 76 },
      { id: "p06", nome: "Pulgar",        posicao: "MEI", overall: 77 },
      { id: "p07", nome: "De la Cruz",    posicao: "MEI", overall: 83 },
      { id: "p08", nome: "Gerson",        posicao: "MEI", overall: 80 },
      { id: "p09", nome: "Arrascaeta",    posicao: "MEI", overall: 87 },
      { id: "p10", nome: "Bruno Henrique",posicao: "ATK", overall: 79 },
      { id: "p11", nome: "Gabigol",       posicao: "ATK", overall: 84 },
      { id: "p12", nome: "Pedro",         posicao: "ATK", overall: 86 },
    ]
  },
  {
    id: "palmeiras",
    nome: "Palmeiras",
    sigla: "PAL",
    cor: "#006437",
    jogadores: [
      { id: "p13", nome: "Weverton",      posicao: "GOL", overall: 85 },
      { id: "p14", nome: "Marcos Rocha",  posicao: "DEF", overall: 74 },
      { id: "p15", nome: "Murilo",        posicao: "DEF", overall: 80 },
      { id: "p16", nome: "Gustavo Gómez", posicao: "DEF", overall: 83 },
      { id: "p17", nome: "Piquerez",      posicao: "DEF", overall: 78 },
      { id: "p18", nome: "Aníbal Moreno", posicao: "MEI", overall: 79 },
      { id: "p19", nome: "Raphael Veiga", posicao: "MEI", overall: 85 },
      { id: "p20", nome: "Zé Rafael",     posicao: "MEI", overall: 76 },
      { id: "p21", nome: "Estêvão",       posicao: "MEI", overall: 82 },
      { id: "p22", nome: "Rony",          posicao: "ATK", overall: 77 },
      { id: "p23", nome: "Flaco López",   posicao: "ATK", overall: 80 },
      { id: "p24", nome: "Endrick",       posicao: "ATK", overall: 81 },
    ]
  },
  {
    id: "corinthians",
    nome: "Corinthians",
    sigla: "COR",
    cor: "#000000",
    jogadores: [
      { id: "p25", nome: "Hugo Souza",    posicao: "GOL", overall: 78 },
      { id: "p26", nome: "Fagner",        posicao: "DEF", overall: 73 },
      { id: "p27", nome: "Gil",           posicao: "DEF", overall: 74 },
      { id: "p28", nome: "Félix Torres",  posicao: "DEF", overall: 76 },
      { id: "p29", nome: "Hugo",          posicao: "DEF", overall: 70 },
      { id: "p30", nome: "Raniele",       posicao: "MEI", overall: 72 },
      { id: "p31", nome: "Charles",       posicao: "MEI", overall: 75 },
      { id: "p32", nome: "Rodrigo Garro", posicao: "MEI", overall: 82 },
      { id: "p33", nome: "Wesley",        posicao: "MEI", overall: 74 },
      { id: "p34", nome: "Romero",        posicao: "ATK", overall: 76 },
      { id: "p35", nome: "Yuri Alberto",  posicao: "ATK", overall: 80 },
      { id: "p36", nome: "Memphis",       posicao: "ATK", overall: 83 },
    ]
  },
  {
    id: "saopulo",
    nome: "São Paulo",
    sigla: "SPF",
    cor: "#CC0000",
    jogadores: [
      { id: "p37", nome: "Rafael",        posicao: "GOL", overall: 80 },
      { id: "p38", nome: "Rafinha",       posicao: "DEF", overall: 73 },
      { id: "p39", nome: "Arboleda",      posicao: "DEF", overall: 77 },
      { id: "p40", nome: "Alan Franco",   posicao: "DEF", overall: 75 },
      { id: "p41", nome: "Welington",     posicao: "DEF", overall: 74 },
      { id: "p42", nome: "Luiz Gustavo",  posicao: "MEI", overall: 73 },
      { id: "p43", nome: "Alisson",       posicao: "MEI", overall: 76 },
      { id: "p44", nome: "Nestor",        posicao: "MEI", overall: 74 },
      { id: "p45", nome: "Lucas",         posicao: "MEI", overall: 81 },
      { id: "p46", nome: "Ferreira",      posicao: "ATK", overall: 75 },
      { id: "p47", nome: "Calleri",       posicao: "ATK", overall: 82 },
      { id: "p48", nome: "Luciano",       posicao: "ATK", overall: 78 },
    ]
  },
  {
    id: "atleticomg",
    nome: "Atlético-MG",
    sigla: "CAM",
    cor: "#000000",
    jogadores: [
      { id: "p49", nome: "Everson",       posicao: "GOL", overall: 81 },
      { id: "p50", nome: "Mariano",       posicao: "DEF", overall: 72 },
      { id: "p51", nome: "Jemerson",      posicao: "DEF", overall: 74 },
      { id: "p52", nome: "Guilherme",     posicao: "DEF", overall: 76 },
      { id: "p53", nome: "Arana",         posicao: "DEF", overall: 79 },
      { id: "p54", nome: "Otávio",        posicao: "MEI", overall: 77 },
      { id: "p55", nome: "Battaglia",     posicao: "MEI", overall: 75 },
      { id: "p56", nome: "Rubens",        posicao: "MEI", overall: 73 },
      { id: "p57", nome: "Paulinho",      posicao: "MEI", overall: 82 },
      { id: "p58", nome: "Vargas",        posicao: "ATK", overall: 78 },
      { id: "p59", nome: "Hulk",          posicao: "ATK", overall: 80 },
      { id: "p60", nome: "Deyverson",     posicao: "ATK", overall: 75 },
    ]
  },
  {
    id: "internacional",
    nome: "Internacional",
    sigla: "INT",
    cor: "#CC0000",
    jogadores: [
      { id: "p61", nome: "Rochet",        posicao: "GOL", overall: 82 },
      { id: "p62", nome: "Bustos",        posicao: "DEF", overall: 73 },
      { id: "p63", nome: "Vitão",         posicao: "DEF", overall: 77 },
      { id: "p64", nome: "Mercado",       posicao: "DEF", overall: 74 },
      { id: "p65", nome: "Renê",          posicao: "DEF", overall: 72 },
      { id: "p66", nome: "Rômulo",        posicao: "MEI", overall: 74 },
      { id: "p67", nome: "Bruno Gomes",   posicao: "MEI", overall: 73 },
      { id: "p68", nome: "Alan Patrick",  posicao: "MEI", overall: 84 },
      { id: "p69", nome: "Wesley",        posicao: "MEI", overall: 76 },
      { id: "p70", nome: "Wanderson",     posicao: "ATK", overall: 75 },
      { id: "p71", nome: "Borré",         posicao: "ATK", overall: 81 },
      { id: "p72", nome: "Valencia",      posicao: "ATK", overall: 77 },
    ]
  },
  {
    id: "gremio",
    nome: "Grêmio",
    sigla: "GRE",
    cor: "#3B77BB",
    jogadores: [
      { id: "p73", nome: "Marchesín",     posicao: "GOL", overall: 80 },
      { id: "p74", nome: "João Pedro",    posicao: "DEF", overall: 71 },
      { id: "p75", nome: "Geromel",       posicao: "DEF", overall: 73 },
      { id: "p76", nome: "Kannemann",     posicao: "DEF", overall: 75 },
      { id: "p77", nome: "Reinaldo",      posicao: "DEF", overall: 72 },
      { id: "p78", nome: "Dodi",          posicao: "MEI", overall: 74 },
      { id: "p79", nome: "Pepê",          posicao: "MEI", overall: 78 },
      { id: "p80", nome: "Carballo",      posicao: "MEI", overall: 73 },
      { id: "p81", nome: "Cristaldo",     posicao: "MEI", overall: 80 },
      { id: "p82", nome: "Soteldo",       posicao: "ATK", overall: 79 },
      { id: "p83", nome: "Braithwaite",   posicao: "ATK", overall: 78 },
      { id: "p84", nome: "Diego Costa",   posicao: "ATK", overall: 76 },
    ]
  },
  {
    id: "botafogo",
    nome: "Botafogo",
    sigla: "BOT",
    cor: "#000000",
    jogadores: [
      { id: "p85", nome: "John",          posicao: "GOL", overall: 79 },
      { id: "p86", nome: "Damián Suárez", posicao: "DEF", overall: 74 },
      { id: "p87", nome: "Bastos",        posicao: "DEF", overall: 75 },
      { id: "p88", nome: "Alexander Barboza", posicao: "DEF", overall: 77 },
      { id: "p89", nome: "Marçal",        posicao: "DEF", overall: 73 },
      { id: "p90", nome: "Gregore",       posicao: "MEI", overall: 75 },
      { id: "p91", nome: "Marlon Freitas",posicao: "MEI", overall: 78 },
      { id: "p92", nome: "Eduardo",       posicao: "MEI", overall: 74 },
      { id: "p93", nome: "Tchê Tchê",     posicao: "MEI", overall: 73 },
      { id: "p94", nome: "Júnior Santos", posicao: "ATK", overall: 77 },
      { id: "p95", nome: "Tiquinho",      posicao: "ATK", overall: 82 },
      { id: "p96", nome: "Savarino",      posicao: "ATK", overall: 80 },
    ]
  }
];
